### ISSUE TITLE
请问需要自己下载Chatglm-6B模型到本机中进行部署吗

### ISSUE THREAD

**Issue by Weihong-Liu** [thomas-yanxin/LangChain-ChatGLM-Webui#1]
由于此项目涉及到上传文件操作，会不会涉及到数据泄漏的问题

**Comment by thomas-yanxin** [comment]
1. 项目支持离线部署，您可以clone下来自行体验（如果您设备支持的话）
2. 在ModelScope平台体验可能会涉及您担忧的问题，但平台（阿里云应该会做风险把控）应该不会留存数据并且部署代码公开透明。
3. 如果您的数据隐私风险**非常**高，可能更倾向您离线部署。

**Comment by Weihong-Liu** [comment]
好的好的，谢谢！
