### ISSUE TITLE
您好，支持的知识库都有什么？知识库可以为知识图谱吗？

### ISSUE THREAD

**Issue by swx-10** [thomas-yanxin/LangChain-ChatGLM-Webui#10]
如题，期待您的回复！

**Comment by thomas-yanxin** [comment]
您好，目前支持的主要是一些文本型的知识库（如.pdf、.docx、.txt、.md），后面会提供一些包括维基百科在内的知识库。您所说的知识图谱，目前暂时是不支持的。我需要调研一下相关方面才能给你进一步的答复。

**Comment by swx-10** [comment]
> 

好的，感谢您的回复
