### ISSUE TITLE
public link链接timeout

### ISSUE THREAD

**Issue by navfour** [thomas-yanxin/LangChain-ChatGLM-Webui#113]
openi上拉取运行后发现之后localhost地址，没有public地址🤔（share已设为true）
*** Failed to connect to ec2.gradio.app:22: [Errno 110] Connection timed out

**Comment by thomas-yanxin** [comment]
public 地址需要链到国外走一圈，time out的原因和你日常不加国内镜像源pip install 的时候出现time out的原因一样。

**Comment by navfour** [comment]
> public 地址需要链到国外走一圈，time out的原因和你日常不加国内镜像源pip install 的时候出现time out的原因一样。
所以是……openi计算集群的网络环境问题？🤔

**Comment by LHY-Distance** [comment]
> > public 地址需要链到国外走一圈，time out的原因和你日常不加国内镜像源pip install 的时候出现time out的原因一样。
> > 所以是……openi计算集群的网络环境问题？🤔

请问您最后怎么解决的呀？是换一个智算集群吗还是连外网？

**Comment by thomas-yanxin** [comment]
> > > public 地址需要链到国外走一圈，time out的原因和你日常不加国内镜像源pip install 的时候出现time out的原因一样。
> > > 所以是……openi计算集群的网络环境问题？🤔
> 
> 请问您最后怎么解决的呀？是换一个智算集群吗还是连外网？

这两个都解决不了。本地有卡就拉到本地跑，本地没卡去autodl或者pai跑。

**Comment by LHY-Distance** [comment]
那我想问一下，我把local url换成http://127.0.0.1:7860之后，还是打不开的，显示
无法访问此页面

127.0.0.1&nbsp;已拒绝连接
但是我不加端口号，直接打开127.0.0.1是有蓝色那个页面出现的，所以IIS应该是没有问题的。
可以问一下为什么local url也访问不了嘛？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年2月18日(星期天) 晚上11:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [X-D-Lab/LangChain-ChatGLM-Webui] public link链接timeout (Issue #113)





    
public 地址需要链到国外走一圈，time out的原因和你日常不加国内镜像源pip install 的时候出现time out的原因一样。
 所以是……openi计算集群的网络环境问题？🤔
   
请问您最后怎么解决的呀？是换一个智算集群吗还是连外网？
  
这两个都解决不了。本地有卡就拉到本地跑，本地没卡去autodl或者pai跑。

**Comment by thomas-yanxin** [comment]
> 那我想问一下，我把local url换成[http://127.0.0.1:7860之后，还是打不开的，显示](http://127.0.0.1:7860%E4%B9%8B%E5%90%8E%EF%BC%8C%E8%BF%98%E6%98%AF%E6%89%93%E4%B8%8D%E5%BC%80%E7%9A%84%EF%BC%8C%E6%98%BE%E7%A4%BA) 无法访问此页面 127.0.0.1&nbsp;已拒绝连接 但是我不加端口号，直接打开127.0.0.1是有蓝色那个页面出现的，所以IIS应该是没有问题的。 可以问一下为什么local url也访问不了嘛？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年2月18日(星期天) 晚上11:58 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [X-D-Lab/LangChain-ChatGLM-Webui] public link链接timeout (Issue #113) public 地址需要链到国外走一圈，time out的原因和你日常不加国内镜像源pip install 的时候出现time out的原因一样。 所以是……openi计算集群的网络环境问题？🤔 请问您最后怎么解决的呀？是换一个智算集群吗还是连外网？ 这两个都解决不了。本地有卡就拉到本地跑，本地没卡去autodl或者pai跑。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

7860这个端口平台没有放开啊。
