### ISSUE TITLE
模型加载不成功，但是终端没有报错

### ISSUE THREAD

**Issue by Luka0770** [thomas-yanxin/LangChain-ChatGLM-Webui#118]
![f60332f613cdb7c31d5611117602da8](https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/assets/139829995/00fc7bfd-ff09-4785-b79d-bbbc3ecdf0d7)
![cbb5df7245de1e2f0cd26b1a45fa656](https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/assets/139829995/79bfed83-ba08-4941-b473-8f4d2bcdb4b8)
![675ab9f37f780b3c273afe789c20f06](https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/assets/139829995/7fb977ee-87d2-4c0c-a492-1a21453b9411)

**Comment by JinwenYao** [comment]
你好，请问一下你这个问题解决了吗
