### ISSUE TITLE
RuntimeError: Error in __cdecl faiss::FileIOReader::FileIOReader(const char *) at D:\a\faiss-wheels\faiss-wheels\faiss\faiss\impl\io.cpp:68: Error: 'f' failed: could not open faiss_index\index.faiss for reading: No such file or directory

### ISSUE THREAD

**Issue by DuFangY** [thomas-yanxin/LangChain-ChatGLM-Webui#129]
RuntimeError: Error in __cdecl faiss::FileIOReader::FileIOReader(const char *) at D:\a\faiss-wheels\faiss-wheels\faiss\faiss\impl\io.cpp:68: Error: 'f' failed: could not open faiss_index\index.faiss for reading: No such file or directory

**Comment by thomas-yanxin** [comment]
https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/issues/79
