### ISSUE TITLE
what's the difference between the original repo: langchain-chatglm and this one?

### ISSUE THREAD

**Issue by applepieiris** [thomas-yanxin/LangChain-ChatGLM-Webui#130]
I see this repo has more stars than the original repo: https://github.com/chatchat-space/Langchain-Chatchat. What's the difference between them and which one should I first to try if I want to deploy a local version to chat with uploaded document?

**Comment by thomas-yanxin** [comment]
You can prefer [his](https://github.com/chatchat-space/Langchain-Chatchat) from a maintenance point of view.
