### ISSUE TITLE
gradio无法创建share link

### ISSUE THREAD

**Issue by handsomexiu** [thomas-yanxin/LangChain-ChatGLM-Webui#131]
我用gradio3.10版本最后会报错：*** Failed to connect to ec2.gradio.app:22: [Errno 110] Connection timed out
我用gradio 3.23版本最后会是无法创建share link
然后waget frpc那个还无法waget请问如何结局
本人是自己租的一个服务器做的实验

**Comment by thomas-yanxin** [comment]
自己组的服务器没必要开share。另外gradio不是必要，也可以用API交互。

**Comment by LHY-Distance** [comment]
我用gradio3.10版本会报错：*** Failed to connect to ec2.gradio.app:22: [Errno 110] Connection timed out
用gradio 3.23版本是无法创建share link
wget frpc_linux_amd64_v0.2到gradio之后，也用chmod给了操作的权限，结果是出现了running on local URL：http://0.0.0.0:7860之后等了很久很久 等了一小时，没有报错出现但也没有share URL出现
请问接下来该怎么操作呢
