### ISSUE TITLE
增加类似 OpenAI API 的接口方式

### ISSUE THREAD

**Issue by online2311** [thomas-yanxin/LangChain-ChatGLM-Webui#18]
是否可以增加类似 OpenAI API 的接口方式，可以参考：```https://github.com/ninehills/chatglm-openai-api```

**Comment by thomas-yanxin** [comment]
早上刚看到，感谢建议！

**Comment by thomas-yanxin** [comment]
已提供api接口，但具体设计需要再行斟酌，可以一起参与！

**Comment by ccartermices** [comment]
你好，请问接口api功能已经有了吗？如何使用？

**Comment by thomas-yanxin** [comment]
参照[此文档](https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/blob/master/docs/deploy.md#jina-serving-api)
