### ISSUE TITLE
BELLE-LLaMA-13B-2M 支持 

### ISSUE THREAD

**Issue by online2311** [thomas-yanxin/LangChain-ChatGLM-Webui#19]
我有BELLE-LLaMA-13B-2M 的 模型，如何提供出来给大家使用？

**Comment by thomas-yanxin** [comment]
1. 百度网盘（虽然百度网盘似乎很通用，但是限速的操作着实不太友好）
2. 可以把模型托管在某个平台，然后提供url供大家下载。

我是把所有的模型托管在[这里](https://openi.pcl.ac.cn/Learning-Develop-Union/LangChain-ChatGLM-Webui/datasets)，如果您愿意，我可以拉你进入这个组织，后面有模型都可以在这里托管。

**Comment by online2311** [comment]
ID：``` online2311 ``` 拉我进组织吧，我上传BELLE-LLaMA-13B-2M 模型。

**Comment by thomas-yanxin** [comment]
@online2311 已添加，感谢！

**Comment by online2311** [comment]
收到～

**Comment by online2311** [comment]
你WeChat，我们私聊进度快一些。

**Comment by thomas-yanxin** [comment]
@online2311 yx18962787069

**Comment by online2311** [comment]
@thomas-yanxin 已经加了，可以吧消息删除了。
