### ISSUE TITLE
上传md显示Error，不明确是格式问题还是文件过大

### ISSUE THREAD

**Issue by buttercannfly** [thomas-yanxin/LangChain-ChatGLM-Webui#2]
上传md之后显示error，md中含有代码

**Comment by thomas-yanxin** [comment]
本地部署还是在modelscope上啊？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年04月17日 09:44 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [thomas-yanxin/LangChain-ChatGLM-Webui] 上传md显示Error，不明确是格式问题还是文件过大 (Issue #2) |

上传md之后显示error，md中含有代码

**Comment by thomas-yanxin** [comment]
> 上传md之后显示error，md中含有代码

这个格式是没有问题的。可能产生的问题是：

1. .md文件还没完全上传完成的时候就发送信息了
2. 模型从huggingface下载的时候网络不稳定断了（如果是本地部署的话）

具体需要提供更多的相关信息看一下。

**Comment by lelegogo26** [comment]
<img width="821" alt="1681973308952" src="https://user-images.githubusercontent.com/46149625/233283512-127e94c0-d27c-4aac-a835-792c12052fd5.png">
自己上传的小文件，为什么也会error

**Comment by thomas-yanxin** [comment]
> <img alt="1681973308952" width="821" src="https://user-images.githubusercontent.com/46149625/233283512-127e94c0-d27c-4aac-a835-792c12052fd5.png">
> 
> 自己上传的小文件，为什么也会error

我看了一下日志，从hf拉embedding model的时候网络挂了，抱歉啊

**Comment by zhangd732** [comment]
> > <img alt="1681973308952" width="821" src="https://user-images.githubusercontent.com/46149625/233283512-127e94c0-d27c-4aac-a835-792c12052fd5.png">
> > 自己上传的小文件，为什么也会error
> 
> 我看了一下日志，从hf拉embedding model的时候网络挂了，抱歉啊。后面会和社区同学一起优化在modelscope上的体验，非常抱歉。

我也是一直报ERROR,这个日志在哪里看啊？

**Comment by zhangd732** [comment]
> > 上传md之后显示error，md中含有代码
> 
> 这个格式是没有问题的。可能产生的问题是：
> 
> 1. .md文件还没完全上传完成的时候就发送信息了
> 2. 模型从huggingface下载的时候网络不稳定断了（如果是本地部署的话）
> 
> 具体需要提供更多的相关信息看一下。

如何识别文件上传完成呢？

**Comment by thomas-yanxin** [comment]
> > > 上传md之后显示error，md中含有代码
> > 
> > 
> > 这个格式是没有问题的。可能产生的问题是：
> > 
> > 1. .md文件还没完全上传完成的时候就发送信息了
> > 2. 模型从huggingface下载的时候网络不稳定断了（如果是本地部署的话）
> > 
> > 具体需要提供更多的相关信息看一下。
> 
> 如何识别文件上传完成呢？

https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/issues/11

**Comment by thomas-yanxin** [comment]
> > > <img alt="1681973308952" width="821" src="https://user-images.githubusercontent.com/46149625/233283512-127e94c0-d27c-4aac-a835-792c12052fd5.png">
> > > 自己上传的小文件，为什么也会error
> > 
> > 
> > 我看了一下日志，从hf拉embedding model的时候网络挂了，抱歉啊。后面会和社区同学一起优化在modelscope上的体验，非常抱歉。
> 
> 我也是一直报ERROR,这个日志在哪里看啊？

能否提供一下您运行的大概时间？我看一下具体报错，日志暂时只有我这里可以看。抱歉哈，给你带来了不太好的体验。

**Comment by thomas-yanxin** [comment]
> > > <img alt="1681973308952" width="821" src="https://user-images.githubusercontent.com/46149625/233283512-127e94c0-d27c-4aac-a835-792c12052fd5.png">
> > > 自己上传的小文件，为什么也会error
> > 
> > 
> > 我看了一下日志，从hf拉embedding model的时候网络挂了，抱歉啊。后面会和社区同学一起优化在modelscope上的体验，非常抱歉。
> 
> 我也是一直报ERROR,这个日志在哪里看啊？

ModelScope上的常见问题：
1. 文件没完全上传，就发送信息了，导致获取不到文件地址
2. 从huggingface拉取embedding model的时候网络挂了
3. 用ChatGLM-6B的时候显存爆了
