### ISSUE TITLE
一直提示报错：模型未成功重新加载，请点击重新加载模型

### ISSUE THREAD

**Issue by justin8736** [thomas-yanxin/LangChain-ChatGLM-Webui#21]
按照步骤部署启动了app.py，提示“模型未成功重新加载，请点击重新加载模型”， 这是什么原因
相关的日志信息如下，

Traceback (most recent call last) ──────────────────────╮
│ /content/drive/MyDrive/LangChain-ChatGLM-Webui/app.py:215 in <module>        │
│                                                                              │
│   212 │   return '', history, history                                        │
│   213                                                                        │
│   214                                                                        │
│ ❱ 215 model_status = init_model()                                            │
│   216                                                                        │
│   217 if __name__ == "__main__":                                             │
│   218 │   block = gr.Blocks()                                                │
│                                                                              │
│ /content/drive/MyDrive/LangChain-ChatGLM-Webui/app.py:160 in init_model      │
│                                                                              │
│   157                                                                        │
│   158 def init_model():                                                      │
│   159 │   # try:                                                             │
│ ❱ 160 │   │   knowladge_based_chat_llm.init_model_config()                   │
│   161 │   │   print(knowladge_based_chat_llm.llm._call("你好"))              │
│   162 │   │   return """初始模型已成功加载，可以开始对话"""                  │
│   163 │   # except Exception as e:                                           │
│                                                                              │
│ /content/drive/MyDrive/LangChain-ChatGLM-Webui/app.py:79 in                  │
│ init_model_config                                                            │
│                                                                              │
│    76 │   │   │   model_name=embedding_model_dict[embedding_model], )        │
│    77 │   │   self.embeddings.client = sentence_transformers.SentenceTransfo │
│    78 │   │   │   self.embeddings.model_name, device=EMBEDDING_DEVICE)       │
│ ❱  79 │   │   self.llm.load_llm(llm_device=LLM_DEVICE, num_gpus=num_gpus)    │
│    80 │                                                                      │
│    81 │   def init_knowledge_vector_store(self, filepath):                   │
│    82                                                                        │
│                                                                              │
│ /content/drive/MyDrive/LangChain-ChatGLM-Webui/chatllm.py:126 in load_llm    │
│                                                                              │
│   123 │   │   │   │      device_map: Optional[Dict[str, int]] = None,        │
│   124 │   │   │   │      **kwargs):                                          │
│   125 │   │   if 'chatglm' in self.model_name_or_path.lower():               │
│ ❱ 126 │   │   │   self.tokenizer = AutoTokenizer.from_pretrained(self.model_ │
│   127 │   │   │   │   │   │   │   │   │   │   │   │   │      trust_remote_co │
│   128 │   │   │   if torch.cuda.is_available() and llm_device.lower().starts │
│   129 │   │   │   │   # 根据当前设备GPU数量决定是否进行多卡部署              │
│                                                                              │
│ /usr/local/lib/python3.9/dist-packages/transformers/models/auto/tokenization │
│ _auto.py:692 in from_pretrained                                              │
│                                                                              │
│   689 │   │   │   │   raise ValueError(                                      │
│   690 │   │   │   │   │   f"Tokenizer class {tokenizer_class_candidate} does │
│   691 │   │   │   │   )                                                      │
│ ❱ 692 │   │   │   return tokenizer_class.from_pretrained(pretrained_model_na │
│   693 │   │                                                                  │
│   694 │   │   # Otherwise we have to be creative.                            │
│   695 │   │   # if model is an encoder decoder, the encoder tokenizer class  │
│                                                                              │
│ /usr/local/lib/python3.9/dist-packages/transformers/tokenization_utils_base. │
│ py:1812 in from_pretrained                                                   │
│                                                                              │
│   1809 │   │   │   else:                                                     │
│   1810 │   │   │   │   logger.info(f"loading file {file_path} from cache at  │
│   1811 │   │                                                                 │
│ ❱ 1812 │   │   return cls._from_pretrained(                                  │
│   1813 │   │   │   resolved_vocab_files,                                     │
│   1814 │   │   │   pretrained_model_name_or_path,                            │
│   1815 │   │   │   init_configuration,                                       │
│                                                                              │
│ /usr/local/lib/python3.9/dist-packages/transformers/tokenization_utils_base. │
│ py:1878 in _from_pretrained                                                  │
│                                                                              │
│   1875 │   │   │   # For backward compatibility with odl format.             │
│   1876 │   │   │   if isinstance(init_kwargs["auto_map"], (tuple, list)):    │
│   1877 │   │   │   │   init_kwargs["auto_map"] = {"AutoTokenizer": init_kwar │
│ ❱ 1878 │   │   │   init_kwargs["auto_map"] = add_model_info_to_auto_map(     │
│   1879 │   │   │   │   init_kwargs["auto_map"], pretrained_model_name_or_pat │
│   1880 │   │   │   )                                                         │
│   1881                                                                       │
│                                                                              │
│ /usr/local/lib/python3.9/dist-packages/transformers/utils/generic.py:563 in  │
│ add_model_info_to_auto_map                                                   │
│                                                                              │
│   560 │   """                                                                │
│   561 │   for key, value in auto_map.items():                                │
│   562 │   │   if isinstance(value, (tuple, list)):                           │
│ ❱ 563 │   │   │   auto_map[key] = [f"{repo_id}--{v}" if "--" not in v else v │
│   564 │   │   else:                                                          │
│   565 │   │   │   auto_map[key] = f"{repo_id}--{value}" if "--" not in value │
│   566                                                                        │
│                                                                              │
│ /usr/local/lib/python3.9/dist-packages/transformers/utils/generic.py:563 in  │
│ <listcomp>                                                                   │
│                                                                              │
│   560 │   """                                                                │
│   561 │   for key, value in auto_map.items():                                │
│   562 │   │   if isinstance(value, (tuple, list)):                           │
│ ❱ 563 │   │   │   auto_map[key] = [f"{repo_id}--{v}" if "--" not in v else v │
│   564 │   │   else:                                                          │
│   565 │   │   │   auto_map[key] = f"{repo_id}--{value}" if "--" not in value │
│   566                                                                        │
╰──────────────────────────────────────────────────────────────────────────────╯
TypeError: argument of type 'NoneType' is not iterable

**Comment by thomas-yanxin** [comment]
https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/blob/d3151a01e7b239524039cb3f951b0fcac603fd21/app.py#L21

模型这里修改正确么？
