### ISSUE TITLE
给个建议：requirements.txt 最好指定下版本，直接下载最新的可能会有冲突

### ISSUE THREAD

**Issue by godlockin** [thomas-yanxin/LangChain-ChatGLM-Webui#22]
比如 wandb 最新的是 0.13.5，但是会有接口被迁移掉了，需要降版本（ 0.13.0可以用）才行

**Comment by thomas-yanxin** [comment]
这个可以提个PR么？感谢！

**Comment by godlockin** [comment]
我直接freeze出来的requirements太长了

https://raw.githubusercontent.com/godlockin/LangChain-ChatGLM-Webui/master/requirements.txt

用`pipreqs`搞出来的又太少了，还没想到什么好办法可以弄一组完整的出来
```
accelerate==0.18.0
duckduckgo_search==2.8.6
fschat==0.2.3
gradio==3.27.0
langchain==0.0.147
nltk==3.8.1
sentence_transformers==2.2.2
torch==2.0.0
transformers==4.29.0.dev0
```

**Comment by thomas-yanxin** [comment]
现在的requirements.txt已指定，欢迎测试反馈！感谢！
