### ISSUE TITLE
langchain-serve 集成

### ISSUE THREAD

**Issue by zac-li** [thomas-yanxin/LangChain-ChatGLM-Webui#23]
Hey 我是来自 [langchain-serve](https://github.com/jina-ai/langchain-serve) 的dev！

请问你们在langchain部分的集成有线上的场景吗？

如果有可以考虑了解下我们的产品，方便把langchain部署在云端：

- Exposes APIs from function definitions locally as well as on the cloud.
- Very few lines of code changes, ease of development remains the same as local.
- Supports both REST & Websocket endpoints
- Serverless/autoscaling endpoints with automatic tls certs.
- Real-time streaming, human-in-the-loop support

谢谢

**Comment by thomas-yanxin** [comment]
正在利用LangChain-serve做这部分，感谢并请保持关注！

**Comment by thomas-yanxin** [comment]
已集成langchain-serve！感谢关注！

**Comment by zac-li** [comment]
赞！如有问题请联系我我们，谢谢！！
