### ISSUE TITLE
新版本和视频不太匹配

### ISSUE THREAD

**Issue by laobiao139** [thomas-yanxin/LangChain-ChatGLM-Webui#26]
整个流程跑完了，也正常启动，终端打印的日志中只有127.0.0.1,但是没有外网访问地址，而且使用的是CPU访问，请问是哪一个步骤不对吗？

**Comment by laobiao139** [comment]
已经按照视频降级了。

**Comment by thomas-yanxin** [comment]
新版本需要在原有的镜像中再pip install -r requirements.txt安装一下原镜像没有的如fschat等安装包，另外fschat安装包会强制将gradio升级为3.23.0，因此需要再这之后再进行降级。从你的日志来看，日志均正常。是否是cpu执行应当看一下显存占用。
