### ISSUE TITLE
有办法可以使用chatglm的api方法进行调用吗？

### ISSUE THREAD

**Issue by lwj44542** [thomas-yanxin/LangChain-ChatGLM-Webui#3]
有办法可以使用chatglm的api方法进行调用吗？

**Comment by thomas-yanxin** [comment]
后面会提供minimax的api调用，chatglm130B的api我没拿到所以就…

**Comment by lwj44542** [comment]
minimax也是新的中文大模型吗，您看咱们能不能加个联系方式交流一下？我给您邮箱发邮件？

**Comment by thomas-yanxin** [comment]
> minimax也是新的中文大模型吗，您看咱们能不能加个联系方式交流一下？我给您邮箱发邮件？

可以的。
