### ISSUE TITLE
模型未成功重新加载，请点击重新加载模型

### ISSUE THREAD

**Issue by liningwangyi** [thomas-yanxin/LangChain-ChatGLM-Webui#36]
embedding_model_dict = {
    "ernie-base": "D:/AIL/workspace/LangChain-ChatGLM-Webui/models/ernie-3.0-base-zh",
    "simbert-base-chinese": "D:/AIL/workspace/LangChain-ChatGLM-Webui/models/simbert-base-chinese",
    "text2vec-base": "D:/AIL/workspace/LangChain-ChatGLM-Webui/models/text2vec-large-chinese"

}

llm_model_dict = {
    "ChatGLM-6B-int4": "D:/AIL/workspace/LangChain-ChatGLM-Webui/models/chatglm-6b-int4",
    "BELLE-LLaMA-7B-2M": "D:/AIL/workspace/LangChain-ChatGLM-Webui/models/BELLE-LLaMA-7B-2M"
}

配置的绝对地址路径

**Comment by thomas-yanxin** [comment]
检查日志，看具体报错

**Comment by liningwangyi** [comment]
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
No sentence-transformers model found with name D:/AIL/workspace/LangChain-ChatGLM-Webui/models/text2vec-large-chinese. Creating a new one with MEAN pooling.
No sentence-transformers model found with name D:/AIL/workspace/LangChain-ChatGLM-Webui/models/text2vec-large-chinese. Creating a new one with MEAN pooling.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.

**Comment by liningwangyi** [comment]
解决了，路径应该这么写
embedding_model_dict = {
    "ernie-base": "D:\\AIL\\workspace\\LangChain-ChatGLM-Webui\\models\\ernie-3.0-base-zh",
    "simbert-base-chinese": "D:\\AIL\\workspace\\LangChain-ChatGLM-Webui\\models\\simbert-base-chinese",
    "text2vec-base": "D:\\AIL\\workspace\\LangChain-ChatGLM-Webui\\models\\text2vec-large-chinese"
}

**Comment by ccartermices** [comment]
windows下的路径怎么选择？一直报错：

# model config
embedding_model_dict = {
    "text2vec-base": "E:\langchain-chatGLM-webui\LangChain-ChatGLM-Webui\model_cache\GanymedeNil\text2vec-base-chinese",
    'simbert-base-chinese': 'E:\langchain-chatGLM-webui\LangChain-ChatGLM-Webui\model_cache\WangZeJun\simbert-base-chinese',
}


No sentence-transformers model found with name E:\langchain-chatGLM-webui\LangChain-ChatGLM-Webui\model_cache\WangZeJun\simbert-base-chinese. Creating a new one with MEAN pooling.
No sentence-transformers model found with name E:\langchain-chatGLM-webui\LangChain-ChatGLM-Webui\model_cache\WangZeJun\simbert-base-chinese. Creating a new one with MEAN pooling.
No sentence-transformers model found with name E:\langchain-chatGLM-webui\LangChain-ChatGLM-Webui\model_cache\WangZeJun\simbert-base-chinese. Creating a new one with MEAN pooling.
No sentence-transformers model found with name E:\langchain-chatGLM-webui\LangChain-ChatGLM-Webui\model_cache\WangZeJun\simbert-base-chinese. Creating a new one with MEAN pooling.

**Comment by thomas-yanxin** [comment]
两个斜杠…

**Comment by thomas-yanxin** [comment]
![image](https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/assets/58030051/efef1af3-6e72-4e72-aefe-900a40c19628)

**Comment by ccartermices** [comment]
还是不行
No sentence-transformers model found with name E:\langchain-chatGLM-webui\LangChain-ChatGLM-Webui\model_cache\GanymedeNil\text2vec-base-chinese. Creating a new one with MEAN pooling.


# model config
embedding_model_dict = {
    "text2vec-base": "E:\\langchain-chatGLM-webui\\LangChain-ChatGLM-Webui\\model_cache\\GanymedeNil\\text2vec-base-chinese",
    'simbert-base-chinese': 'E:\\langchain-chatGLM-webui\\LangChain-ChatGLM-Webui\\model_cache\WangZeJun\\simbert-base-chinese',
}

![$KBE(0MGSB@8Q}U{9}BACUT](https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/assets/39996331/974fa33e-5e5d-4338-88ef-b05e8d6f6392)

**Comment by ccartermices** [comment]
还是不行
No sentence-transformers model found with name E:\langchain-chatGLM-webui\LangChain-ChatGLM-Webui\model_cache\GanymedeNil\text2vec-base-chinese. Creating a new one with MEAN pooling.
![$KBE(0MGSB@8Q}U{9}BACUT](https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/assets/39996331/c0aa90c3-c942-4ed2-947a-e081433a6e43)
![$P6M~YJ@RUD$A~@SOYM3@EG](https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/assets/39996331/429c2b30-392a-47be-9258-4d711e2f6855)

**Comment by thomas-yanxin** [comment]
> 还是不行 No sentence-transformers model found with name E:\langchain-chatGLM-webui\LangChain-ChatGLM-Webui\model_cache\GanymedeNil\text2vec-base-chinese. Creating a new one with MEAN pooling. ![$KBE(0MGSB@8Q}U{9}BACUT](https://user-images.githubusercontent.com/39996331/241705767-c0aa90c3-c942-4ed2-947a-e081433a6e43.png) ![$P6MYJ@RUD$A@SOYM3@EG](https://user-images.githubusercontent.com/39996331/241705788-429c2b30-392a-47be-9258-4d711e2f6855.png)

您发的那一串并不影响最终结果。

**Comment by thomas-yanxin** [comment]
> 还是不行 No sentence-transformers model found with name E:\langchain-chatGLM-webui\LangChain-ChatGLM-Webui\model_cache\GanymedeNil\text2vec-base-chinese. Creating a new one with MEAN pooling. ![$KBE(0MGSB@8Q}U{9}BACUT](https://user-images.githubusercontent.com/39996331/241705767-c0aa90c3-c942-4ed2-947a-e081433a6e43.png) ![$P6MYJ@RUD$A@SOYM3@EG](https://user-images.githubusercontent.com/39996331/241705788-429c2b30-392a-47be-9258-4d711e2f6855.png)

您这里需要把init_llm改为ChatGLM-6b-int4

**Comment by ccartermices** [comment]
改成int4了，但是还是不行：
![@X20@GRG W_1}_3%I0P1VTH](https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/assets/39996331/14a9c890-eb7b-4886-bdcd-122de39a0880)

**Comment by thomas-yanxin** [comment]
> 改成int4了，但是还是不行： ![@X20@GRG W_1}_3%I0P1VTH](https://user-images.githubusercontent.com/39996331/241717524-14a9c890-eb7b-4886-bdcd-122de39a0880.png)

https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/issues/69#issuecomment-1572247002
