### ISSUE TITLE
本地下载好的模型到底放在哪里啊

### ISSUE THREAD

**Issue by Maddaxman** [thomas-yanxin/LangChain-ChatGLM-Webui#37]
<img width="818" alt="image" src="https://user-images.githubusercontent.com/31379908/234462747-ebce26e1-ea17-491d-84ff-4c7ec9ac9500.png">

<img width="539" alt="image" src="https://user-images.githubusercontent.com/31379908/234463235-356ebb9f-181c-40f1-bc43-6c8e91e9211b.png">

要怎么改啊，怎么放都模型未加载，绝对路径也放过了，能不能搞个教程啊

**Comment by thomas-yanxin** [comment]
![image](https://user-images.githubusercontent.com/58030051/234467107-92643b30-593c-4e08-a695-dd6d0315e08c.png)
![image](https://user-images.githubusercontent.com/58030051/234467248-5e24ff5e-6f5a-438d-8ea7-ee798a8bc951.png)

**Comment by Maddaxman** [comment]
@thomas-yanxin 大佬 不行哦
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/31379908/234470622-2135d8d3-07c9-4063-9b01-98deadae20dd.png">
<img width="1068" alt="image" src="https://user-images.githubusercontent.com/31379908/234470737-731e9ef3-3f9d-43e1-abbd-e8c5066f69c7.png">
<img width="972" alt="image" src="https://user-images.githubusercontent.com/31379908/234470908-e2d17d02-b18d-472c-9883-7dd056e4bb75.png">
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/31379908/234470991-ec53182a-3520-4f4e-8a13-7076e7679bf6.png">
控制台没报啥

**Comment by thomas-yanxin** [comment]
你这里的路径看着不太对欸

**Comment by Maddaxman** [comment]
@thomas-yanxin 怎么说，我是wsl里的ubuntu

**Comment by godlockin** [comment]
text2vec 的路径里 \ 和 / 是不是有问题？
在项目运行的路径里 ls $PATH_TO_MODEL 看看能不能访问到

**Comment by 7NGU** [comment]
> @thomas-yanxin 怎么说，我是wsl里的ubuntu

我也是wsl中的ubuntu，遇到了相同的问题。后面发现是用“unzip -d xxx xxx.zip”命令解压LLM model的时候会重复一个xxx文件夹，这个文件夹在vs code里面会被自动折叠起来，把它拿出来或者更改路径就可以正常加载了。

**Comment by koalasxm** [comment]
大佬们，我在执行python3 app.py时，就报错了，大家有遇到过吗？
![image](https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/assets/54502762/1690f70c-7d36-474c-a551-1b2c84e1c434)

**Comment by bzjf** [comment]
> @thomas-yanxin 大佬 不行哦 <img alt="image" width="1041" src="https://user-images.githubusercontent.com/31379908/234470622-2135d8d3-07c9-4063-9b01-98deadae20dd.png"> <img alt="image" width="1068" src="https://user-images.githubusercontent.com/31379908/234470737-731e9ef3-3f9d-43e1-abbd-e8c5066f69c7.png"> <img alt="image" width="972" src="https://user-images.githubusercontent.com/31379908/234470908-e2d17d02-b18d-472c-9883-7dd056e4bb75.png"> <img alt="image" width="1023" src="https://user-images.githubusercontent.com/31379908/234470991-ec53182a-3520-4f4e-8a13-7076e7679bf6.png"> 控制台没报啥

相对路径应该是./ 或者直接省略 
以/开头表示的是从根目录开始的绝对路径 所以你的写法是不对的
