### ISSUE TITLE
再冒昧的提倆建议

### ISSUE THREAD

**Issue by godlockin** [thomas-yanxin/LangChain-ChatGLM-Webui#39]
1. https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/blob/d93d439e2663b4297e73f50d16af4f382892db69/app.py#L313

这个地方可以多配些参数

demo.queue(concurrency_count=3
           ).launch(server_name='0.0.0.0',
                    server_port=17861,
                    show_api=False,
                    share=True,
                    inbrowser=False)

2. 注释尽量用英文，在非utf-8默认的系统里面，中文全是乱码

**Comment by thomas-yanxin** [comment]
收到！感谢建议！第一点方便的话可以提一下pr～感谢！
