### ISSUE TITLE
Something went wrong Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by gsshawn** [thomas-yanxin/LangChain-ChatGLM-Webui#45]
Something went wrong
Expecting value: line 1 column 1 (char 0)，加载本地模型后，输入问题后提交，报的错误，不知道是什么原因。

**Comment by weifan-zhao** [comment]
同问！模型加载成功后，不管输不输入文件，只要输入问题就会报错，然后想要重新输入问题又得重新加载模型

**Comment by thomas-yanxin** [comment]
gradio的版本发一下

**Comment by weifan-zhao** [comment]
3.23.0

**Comment by thomas-yanxin** [comment]
https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/issues/54
