### ISSUE TITLE
提示错误Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by haorengx** [thomas-yanxin/LangChain-ChatGLM-Webui#54]
按步骤完成相关设置后，模型都可以了，也完全上传文件了，但一问问题就会提示，提示错误Expecting value: line 1 column 1 (char 0)，无法运行。
![sunlogin_20230508165812](https://user-images.githubusercontent.com/52776256/236783458-b027723e-4bbb-4df5-8273-792ac359fa70.jpg)

**Comment by thomas-yanxin** [comment]
发一下gradio的版本

**Comment by thomas-yanxin** [comment]
关掉代理试试？

**Comment by haorengx** [comment]
你好，关了代理后，的确可以了。
