### ISSUE TITLE
在线演示不能用

### ISSUE THREAD

**Issue by greatliu** [thomas-yanxin/LangChain-ChatGLM-Webui#58]
你好，想试一下demo的效果，发现两个网站的demo都各种error。

**Comment by thomas-yanxin** [comment]
您提供的信息不足以定位问题，请提供测试时间方便定位。

另外今天发现的问题是：Jina提供的embedding inference的credit用完了，这也可能是导致您测试error的原因。

感谢反馈。

**Comment by greatliu** [comment]
> 
您好，感谢回复。
就在我发这个回复的时间，又测试了一下，两个网站的demo还是秒报error。
我只是问了一句“你是谁”，就直接报error。

不知这信息够吗？不是专业人员，不好意思。

**Comment by thomas-yanxin** [comment]
我查看了HuggingFace平台上的log，没有找到“你是谁”的相关query。

我总结了一下huggingface平台我刚刚看到的几个问题：
1. 没有上传知识库文件就直接发送query，没有获取到相关的文件导致error；
2. 上传的是pdf文件，huggingface平台上没有安装加载pdf文件所需要的依赖包，因此发送pdf是会error的。

**Comment by greatliu** [comment]
您好。
前面我的确没上传知识库，我以为系统自带了语言模型。
我刚才又试了下，上传了几个手头的nlp训练文本集（txt格式）、几篇毕设论文（docx格式）、还有您截图中[ChatGLM-6B]的readme（md格式）文件进行测试。除了有了几秒的loading时间，返回结果还是error啊。

有没有什么可以试用的文本集链接？我想知道上传的文本集得是什么格式才能用。

**Comment by hanzhenlei767** [comment]
我的问题也是一样的

**Comment by thomas-yanxin** [comment]
确认：在线演示均可用

若不可用请提供：
1. 测试平台（HuggingFace/ModelScope/AIStudio）
2. 测试时间
3. 测试问题（若方便提供的话）
