### ISSUE TITLE
初次运行报错

### ISSUE THREAD

**Issue by leeyt1234** [thomas-yanxin/LangChain-ChatGLM-Webui#59]
显示模块找不到，但是pip装不了这么模块

  from duckduckgo_search.utils import Session
ModuleNotFoundError: No module named 'duckduckgo_search.utils'

**Comment by leeyt1234** [comment]
我知道了，权限问题，我的环境，需要root权限，只能sudo来运行

**Comment by sxada** [comment]
我也遇到了同样的情况duckduckgo_search.utils 找不到，不知道怎么搞

**Comment by lialzm** [comment]
> 我也遇到了同样的情况duckduckgo_search.utils 找不到，不知道怎么搞

注释掉那一段就行
