### ISSUE TITLE
输入python3 app.py后没有反应

### ISSUE THREAD

**Issue by ccartermices** [thomas-yanxin/LangChain-ChatGLM-Webui#64]
输入python3 app.py后没有反应，接着尝试输入python app.py提示我：

Traceback (most recent call last):
  File "E:\langchain-chatGLM-webui\LangChain-ChatGLM-Webui\app.py", line 8, in <module>
    from duckduckgo_search.utils import SESSION
ModuleNotFoundError: No module named 'duckduckgo_search.utils'

然后我尝试了使用py app.py运行，结果报错
Traceback (most recent call last):
  File "E:\langchain-chatGLM-webui\LangChain-ChatGLM-Webui\app.py", line 4, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'
但是我已经安装了gradio，并且打开python输入Import也成功，我不知道怎么回事了

另外说一下，在安装requirement.txt里的依赖性的时候无法按照detectron2，于是我按照这个方法：
https://zhuanlan.zhihu.com/p/425631249
安装了，然后才允许的Langchain-chatglm-webui，不知道有没有关系。

**Comment by thomas-yanxin** [comment]
1. 今天更新的相关依赖，尤其是duckduckgo_search指定了版本，可以依据新的requirements.txt安装一下。
2. detectron2原生是不支持windows的，所以在windows上安装detectron2需要踩一些坑，和本项目无关。另外，detectron2仅面对pdf文件时才需要，否则可以将其注释掉。

**Comment by ccartermices** [comment]
好的，谢谢

**Comment by WesissoNB** [comment]
不好意思~我也有一樣的問題，執行python3 app.py也是完全沒有反應...請問大大要怎麼辦呢?
