### ISSUE TITLE
AiStudio和启智的平台都有问题

### ISSUE THREAD

**Issue by zyegao** [thomas-yanxin/LangChain-ChatGLM-Webui#66]
AiStudio上依赖库之间出现问题，按照Notebook内容无法正确安装

启智上使用docker镜像，降级了gradio，但是Embedding model无论怎么选择或者怎么放置都无法正确加载（尝试放在dataset中，并对应修改config.py路径，，或者dataset什么都不放让他自己下载）
![image](https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/assets/15649422/12ce27c9-133b-496f-a453-e73df6f56612)

**Comment by thomas-yanxin** [comment]
看您的截图两个模型不都加载了么？这有什么问题么？

AIStudio上的noteboook虽然描述不完善，但确保可以安装。请自行探索。

**Comment by thomas-yanxin** [comment]
启智平台部署可参考视频：【手把手带你实现：基于Langchain和chatglm-6b构建本地知识库的自动问答应用】 https://www.bilibili.com/video/BV11N411y7dT/?share_source=copy_web&vd_source=8162f92b2a1a94035ca9e4e0f6e1860a
