### ISSUE TITLE
无法通过wget下载模型

### ISSUE THREAD

**Issue by tzwo** [thomas-yanxin/LangChain-ChatGLM-Webui#67]
[1] 175
[2] 176
[3] 177
[4] 178
[5] 179
bash: X-Amz-Credential=1fa9e58b689ws4_request: command not found
bash: X-Amz-Date=2023055405Z: command not found
[6] 180
bash: X-Amz-Expires=6040: command not found
bash: X-Amz-SignedHeaders=host: command not found
bash: response-content-disposition=attachment%3B%20filename: command not found
bash: X-Amz-Signature=d0739fff360451c5413004f9678ad: command not found
[2]   Exit 127                X-Amz-Credential=1fa9e58b6899afd26dd3%2F20230530%2Fus-east-1%2Fs3%2Faws4_request
[3]   Exit 127                X-Amz-Date=2023053405Z
[4]   Exit 127                X-Amz-Expires=6000
[5]-  Exit 127                X-Amz-SignedHeaders=h
[6]+  Exit 127                response-content-disposition=attachment%3%22text2vec-base-chinese.zip%22

**Comment by tzwo** [comment]
> 请参考B站视频：【手把手带你实现：基于Langchain和chatglm-6b构建本地知识库的自动问答应用】 https://www.bilibili.com/video/BV11N411y7dT/?share_source=copy_web&vd_source=8162f92b2a1a94035ca9e4e0f6e1860a

仿照视频大约26分钟时的wget -O操作时出现的上述问题，想问一下有什么解决方法吗

**Comment by thomas-yanxin** [comment]
> > 请参考B站视频：【手把手带你实现：基于Langchain和chatglm-6b构建本地知识库的自动问答应用】 https://www.bilibili.com/video/BV11N411y7dT/?share_source=copy_web&vd_source=8162f92b2a1a94035ca9e4e0f6e1860a
> 
> 仿照视频大约26分钟时的wget -O操作时出现的上述问题，想问一下有什么解决方法吗

把您的完整wget命令贴一下。

**Comment by tzwo** [comment]
wget -O text2vec-base-chinese.zip https://s3.openi.org.cn/opendata/attachment/0/c/0cebbcbc-5e41-4826-9052-718b601790d9?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=1fa9e58b6899afd26dd3%2F20230530%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230530T095405Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3D%22text2vec-base-chinese.zip%22&X-Amz-Signature=d0739fff360451c5413004f9678a0d13897fa387b0b765ba6181c843804e505d

**Comment by tzwo** [comment]
> > > 请参考B站视频：【手把手带你实现：基于Langchain和chatglm-6b构建本地知识库的自动问答应用】 https://www.bilibili.com/video/BV11N411y7dT/?share_source=copy_web&vd_source=8162f92b2a1a94035ca9e4e0f6e1860a
> > 
> > 
> > 仿照视频大约26分钟时的wget -O操作时出现的上述问题，想问一下有什么解决方法吗
> 
> 把您的完整wget命令贴一下。

wget -O text2vec-base-chinese.zip https://s3.openi.org.cn/opendata/attachment/0/c/0cebbcbc-5e41-4826-9052-718b601790d9?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=1fa9e58b6899afd26dd3%2F20230530%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230530T095405Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3D%22text2vec-base-chinese.zip%22&X-Amz-Signature=d0739fff360451c5413004f9678a0d13897fa387b0b765ba6181c843804e505d

**Comment by thomas-yanxin** [comment]
wget -O text2vec-base-chinese.zip 'https://s3.openi.org.cn/opendata/attachment/0/c/0cebbcbc-5e41-4826-9052-718b601790d9?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=1fa9e58b6899afd26dd3%2F20230530%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230530T095405Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3D%22text2vec-base-chinese.zip%22&X-Amz-Signature=d0739fff360451c5413004f9678a0d13897fa387b0b765ba6181c843804e505d'

**Comment by tzwo** [comment]
> wget -O text2vec-base-chinese.zip 'https://s3.openi.org.cn/opendata/attachment/0/c/0cebbcbc-5e41-4826-9052-718b601790d9?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=1fa9e58b6899afd26dd3%2F20230530%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230530T095405Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3D%22text2vec-base-chinese.zip%22&X-Amz-Signature=d0739fff360451c5413004f9678a0d13897fa387b0b765ba6181c843804e505d'

感谢您
