### ISSUE TITLE
本地部署提示没有模型

### ISSUE THREAD

**Issue by xiaohengDa** [thomas-yanxin/LangChain-ChatGLM-Webui#68]
本地部署时找不到模型文件
No sentence-transformers model found with name [C:\Users\Administrator/.cache\torch\sentence_transformers\GanymedeNil_text2vec-base-chinese.](file:///C:/Users/Administrator/.cache/torch/sentence_transformers/GanymedeNil_text2vec-base-chinese.) Creating a new one with MEAN pooling.
No sentence-transformers model found with name [c:\Users\Administrator\LangChain-ChatGLM-Webui\model_cache\GanymedeNil/text2vec-base-chinese\GanymedeNil_text2vec-base-chinese.](file:///C:/Users/Administrator/LangChain-ChatGLM-Webui/model_cache/GanymedeNil/text2vec-base-chinese/GanymedeNil_text2vec-base-chinese.) Creating a new one with MEAN pooling.
不知道是不是我把chatllm.py文件里
#from fastchat.conversation import (compute_skip_echo_len,
                                 #  get_default_conv_template)
这一句给注释掉的原因，但这一句不注释的话会报错
现在就是一直显示加载模型失败，求解答

**Comment by thomas-yanxin** [comment]
你贴的这两行并不影响最终结果。请给出**完整的日志内容、config.py**内容。

另外，issue里有很多找不到模型的issue，可参考相关解决方案。
