### ISSUE TITLE
是否可以加载 safetensors 模型

### ISSUE THREAD

**Issue by online2311** [thomas-yanxin/LangChain-ChatGLM-Webui#7]
我在用 GPTQ-for-LLaMa 压缩模型 
```
CUDA_VISIBLE_DEVICES=0 python llama.py ${MODEL_DIR} c4 --wbits 4 --true-sequential --act-order --groupsize 128 --save_safetensors llama7b-4bit-128g.safetensors
```
项目是否可以加载safetensors 模型

**Comment by thomas-yanxin** [comment]
这个并没有太大影响吧？

**Comment by online2311** [comment]
我主要是确认下，是否可以加载safetensors 的模型。

**Comment by thomas-yanxin** [comment]
> 我主要是确认下，是否可以加载safetensors 的模型。

我看了一下transformers的[代码](https://github.com/huggingface/transformers/blob/main/src/transformers/modeling_utils.py)，应该是支持的。

**Comment by online2311** [comment]
好的，稍后我测试下。感谢🙏
