### ISSUE TITLE
ModuleNotFoundError: No module named 'fastchat.conversation'; 'fastchat' is not a package

### ISSUE THREAD

**Issue by rongweihe** [thomas-yanxin/LangChain-ChatGLM-Webui#71]
阿里云 linux 服务器本地部署

执行 python3 app.py 的时候直接报错

请问有人遇到类似的情况吗

(langchain-webui) [root@ LangChain-ChatGLM-Webui]# python3 app.py
Traceback (most recent call last):
  File "/ai_study/langchain-webui-self/LangChain-ChatGLM-Webui/app.py", line 16, in <module>
    from chatllm import ChatLLM
  File "/ai_study/langchain-webui-self/LangChain-ChatGLM-Webui/chatllm.py", line 5, in <module>
    from fastchat.conversation import (compute_skip_echo_len,
ModuleNotFoundError: No module named 'fastchat.conversation'; 'fastchat' is not a package

**Comment by thomas-yanxin** [comment]
fschat要求python版本要>=3.8，不知道您这里的Python版本是多少？另外能否贴一下fschat的版本

**Comment by lsm03624** [comment]
我碰到这个问题这样解决的：
pip install fastchat fschat
同时安装这个两个包。
