### ISSUE TITLE
mac m1 pro 搭建环境遇到的问题，心累

### ISSUE THREAD

**Issue by shen5455** [thomas-yanxin/LangChain-ChatGLM-Webui#76]
Python 3.10.9        gradio 3.10.0
![image](https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/assets/15943741/21fc48ee-2f4d-4148-ac24-143866b97688)

**1、执行完 python app.py  模型是没有加载成功的，报错如下：**
![image](https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/assets/15943741/f979e24d-f9ba-47cf-878a-bda3502b34fc)

![image](https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/assets/15943741/d5f3c65c-308c-4e84-9add-b0342b290435)
**2、点击页面重新加载模型：**
![image](https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/assets/15943741/b81fcfa7-271c-4144-9b1a-a674b748c951)
![image](https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/assets/15943741/dfba5a19-b755-48a3-927a-48dc88725187)
不管模型有没有加载成功，控制台一直有报错
**3、输入框随便输入，点发送就会报错**
![image](https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/assets/15943741/0081b76a-5a8c-47bb-860b-541436f63a9d)
![image](https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/assets/15943741/c5c990a7-184c-4499-9be7-715762227d87)

**Comment by thomas-yanxin** [comment]
没有mac m1 pro，没做过测试，目测需要改一下加载模型和模型推理那里。
