### ISSUE TITLE
在启智上运行的报错

### ISSUE THREAD

**Issue by shen5455** [thomas-yanxin/LangChain-ChatGLM-Webui#77]
![image](https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/assets/15943741/a6bff80b-79f4-485a-893a-3b88511ae27a)

**Comment by thomas-yanxin** [comment]
用的是我推荐的镜像么`dockerhub.pcl.ac.cn:5000/user-images/openi:LangChain-ChatLLM-2.0`

**Comment by Szysszws** [comment]
> 用的是我推荐的镜像么`dockerhub.pcl.ac.cn:5000/user-images/openi:LangChain-ChatLLM-2.0`

请问启智上面的镜像可以下载到本地吗？
