### ISSUE TITLE
启智社区模型加载成功，但是发送消息时报错没有faiss_index/index.faiss文件

### ISSUE THREAD

**Issue by donger0616** [thomas-yanxin/LangChain-ChatGLM-Webui#79]
RuntimeError: Error in faiss::FileIOReader::FileIOReader(const char*) at /project/faiss/faiss/impl/io.cpp:67: Error: 'f' failed: could not open faiss_index/index.faiss for reading: No such file or directory

**Comment by thomas-yanxin** [comment]
没有点`知识库文件向量化`这个button

**Comment by donger0616** [comment]
已收到

**Comment by TanmayIT09** [comment]
Facing same error while running one streamlit app.
RuntimeError: Error in __cdecl faiss::FileIOReader::FileIOReader(const char *) at D:\a\faiss-wheels\faiss-wheels\faiss\faiss\impl\io.cpp:68: Error: 'f' failed: could not open faiss_index\index.faiss for reading: No such file or directory

**Comment by donger0616** [comment]
已收到

**Comment by TanmayIT09** [comment]
你能帮忙做同样的事吗

**Comment by mohamed3laily** [comment]
how to solve this

**Comment by donger0616** [comment]
已收到
