### ISSUE TITLE
模型加载不成功，但是终端没有显示任何报错

### ISSUE THREAD

**Issue by donger0616** [thomas-yanxin/LangChain-ChatGLM-Webui#80]
![b51ee1ac20b75c84bbd88d52311ed3c](https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/assets/101181892/98eecb43-0d7f-4456-9a38-e2946b4bc471)
上面这个是配置文件
![bab59623b18bc0eea45b1868c25645e](https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/assets/101181892/f2001009-7c88-4f98-ba5e-d9fa9ee287f8)
显示模型加载不成功
![7eb52a117ef5db5871dbe7406bed446](https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/assets/101181892/af5b33b2-bf37-4eae-919a-8b6c2ff82e53)
终端没有任何报错

**Comment by thomas-yanxin** [comment]
init_embedding_model那里写`ernie-base`

**Comment by donger0616** [comment]
![754f2cfe887d2ec8c36df9d0d349b05](https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/assets/101181892/78d1baea-6b60-4bbb-ada1-ed89f25fee0d)
![6cb6bc5ef5ad43c618dce9d7286f9fc](https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/assets/101181892/494185f9-3610-4aa5-9db3-fb0fab760f0c)
老师，还是不行

**Comment by thomas-yanxin** [comment]
额，chatglm-6b-int4那里，你写的是ernie-base的地址……

**Comment by donger0616** [comment]
对哦！可以了！谢谢老师！

**Comment by donger0616** [comment]
老师，现在可以对话了，但是看起来不是很智能

**Comment by donger0616** [comment]
![ad54aa25d8199dc1f47daa97e966cf7](https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/assets/101181892/3baede6b-c862-4fc2-8d4d-8b0eeb2605eb)
终端有提示这个
![65381632f86d0e905f9af1920215ccb](https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/assets/101181892/1ec38e51-b75b-4256-b54a-2e5bd09d596a)
这样是有问题吗
