### ISSUE TITLE
关于“模型未成功重新加载，请点击重新加载模型”的问题

### ISSUE THREAD

**Issue by tanglu86** [thomas-yanxin/LangChain-ChatGLM-Webui#82]
1、config.py配置如下
`
 init model config
#init_llm = "ChatGLM-6B-int8"
init_llm = "ChatGLM-6B"                       #使用的6B模型
init_embedding_model = "text2vec-base"

embedding_model_dict = {
    "text2vec-base": "/data/LangChain/model/text2vec-base-chinese",        
}

llm_model_dict = {
    "chatglm": {
        "ChatGLM-6B": "/data/LangChain/model/chatglm-6b",        #路径已修改
    },
`

2、模型路径确认是正确的
![1](https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/assets/38269740/5e8298f0-9da4-465c-bbd5-4b50c6c39237)

3、web报错
![2](https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/assets/38269740/567e36d5-c11e-47f0-88d9-37c73f3e6cb2)

**Comment by menkeyi** [comment]
遇到同样的问题 不能正常加载模型，后台也没有报错
