### ISSUE TITLE
simbert-base-chinese模型本地已经下载，在config文件下也改为默认，但是模型仍然无法加载

### ISSUE THREAD

**Issue by White-Friday** [thomas-yanxin/LangChain-ChatGLM-Webui#84]
No sentence-transformers model found with name simbert-base-chinese. Creating a new one with MEAN pooling

**Comment by White-Friday** [comment]
RuntimeError: Error in faiss::FileIOReader::FileIOReader(const char*) at /project/faiss/faiss/impl/io.cpp:67: Error: 'f' failed: could not open faiss_index/index.faiss for reading: No such file or directory

**Comment by thomas-yanxin** [comment]
https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/issues/79
