### ISSUE TITLE
模型未成功重新加载

### ISSUE THREAD

**Issue by zhangpeiyu0221newscn** [thomas-yanxin/LangChain-ChatGLM-Webui#86]
你好，我用小白模型搭起来后，也挂载了cache目录，一直提示模型未成功重新加载，请点击重新加载模型，是路径有什么问题吗？
![image](https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/assets/135931302/8f850b4a-82ca-438b-978f-ff7c3cd717d2)

![image](https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/assets/135931302/96aa6084-6fec-489c-85e5-c15e1a188c5f)
![image](https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/assets/135931302/e3b9647a-f330-44c1-90aa-1b09d95e81e6)

**Comment by thomas-yanxin** [comment]
chatglm-6b-int8的路径有问题

**Comment by zhangpeiyu0221newscn** [comment]
路径已改正，但是依旧提示：模型未成功重新加载，请点击重新加载模型

**Comment by zhangpeiyu0221newscn** [comment]
还有个问题，咱们上传知识库文件，对这个文件有没有什么格式要求，有没有demo之类的？

**Comment by thomas-yanxin** [comment]
没有。本项目readme就是个示例。
